"""create_goods

Revision ID: 3babd765cd41
Revises: 
Create Date: 2023-01-31 00:12:47.483021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3babd765cd41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('children', sa.Boolean(), nullable=True),
    sa.Column('displayed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Goods_Catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('catalogue_id', sa.Integer(), nullable=True),
    sa.Column('appeared', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['Category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Goods_Cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogue_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.Column('price_full', sa.Integer(), nullable=True),
    sa.Column('price_with_discount', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedbacks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['Goods_Catalogue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Goods_Cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Goods_Cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards_color',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['Color.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['Goods_Cards.id'], ),
    sa.PrimaryKeyConstraint('color_id', 'goods_id')
    )
    op.create_table('cards_size',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.Column('size_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['Goods_Cards.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['Size.id'], ),
    sa.PrimaryKeyConstraint('size_id', 'goods_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards_size')
    op.drop_table('cards_color')
    op.drop_table('Size')
    op.drop_table('Color')
    op.drop_table('Goods_Cards')
    op.drop_table('Goods_Catalogue')
    op.drop_table('Category')
    # ### end Alembic commands ###
