"""create_goods

Revision ID: 57c7aa6d39f0
Revises: 9c1348b98fec
Create Date: 2023-01-31 00:34:19.010055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c7aa6d39f0'
down_revision = '9c1348b98fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
