"""create_goods

Revision ID: 768df11d5228
Revises: 57c7aa6d39f0
Create Date: 2023-01-31 00:35:41.214759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768df11d5228'
down_revision = '57c7aa6d39f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
