"""create_goods

Revision ID: 8d0806a06559
Revises: 7d0e127c626b
Create Date: 2023-01-31 01:14:38.486969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0806a06559'
down_revision = '7d0e127c626b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Goods_Cards', sa.Column('catalogue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Goods_Cards', 'Goods_Catalogue', ['catalogue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Goods_Cards', type_='foreignkey')
    op.drop_column('Goods_Cards', 'catalogue_id')
    # ### end Alembic commands ###
