"""create_goods

Revision ID: 9c1348b98fec
Revises: a6e076dc6b77
Create Date: 2023-01-31 00:32:30.050798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1348b98fec'
down_revision = 'a6e076dc6b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
