"""create_goods

Revision ID: a6e076dc6b77
Revises: e8bed53e4427
Create Date: 2023-01-31 00:30:02.353517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e076dc6b77'
down_revision = 'e8bed53e4427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
