"""create_goods

Revision ID: e8bed53e4427
Revises: 3babd765cd41
Create Date: 2023-01-31 00:29:06.603935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bed53e4427'
down_revision = '3babd765cd41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
