# Generated by Django 4.1.5 on 2023-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_customuser_login-phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='login-phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер телефона'),
        ),
    ]
